config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'
# ----------------------------------------------
# CRUD
      # get 'messages/:id', to: 'messages#show'
      # post 'messages', to: 'messages#create'
      # put 'messages/:id', to: 'messages#update'
      # delete 'messages/id', to: 'messages#destroy'
      
    # index: show の補助ページ
      # get 'messages', to: 'messages#index'
      
    # new: 新規作成用のフォームページ
      # get 'messages/new', to: 'messages#new'
      
    # edit: 更新用のフォームページ
      # get 'messages/:id/edit', to: 'messages#edit'
# ----------------------------------------------  
# 上記のコードを下記１行でまとめられる
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  
  def index
    @messages = Message.order(id: :desc).page(params[:page]).per(3)
  end
  
  def show
  end
  
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(message_params)
    
    if @message.save
      flash[:success] = 'Messageが正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Messageが投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      flash[:success] = 'Messageは正常終了しました'
      redirect_to @message
    else
      flash.now[:danger] = 'Messageは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @message.destroy
    
    flash[:success] = 'Messageは正常に削除されました'
    redirect_to messages_url
  end
end

private

def set_message
  @message = Message.find(params[:id])
end

# Strong Parameter
def message_params
  params.require(:message).permit(:content, :title)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MessageBoard</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to  '新規メッセージの投稿', new_message_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: message, local: true) do |f| %>
      <% if message.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, 'メッセージ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>id: <%= @message.id %>のメッセージ編集ページ</h1>

<%= render 'form', message: @message %>

app/views/messages/index.html.erb
<h1>メッセージ一覧</h1>

<% if @messages.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>メッセージ</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= link_to message.id, message %></td>
          <td><%= message.title %></td>
          <td><%= message.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @messages %>
  </div>
<% end %>

<%= link_to '新規メッセージの投稿', new_message_path, class: "btn btn-primary" %>

app/views/messages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<h1>id: <%= @message.id %> のメッセージ詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @message.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @message.title %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @message.content %></td>
  </tr>
</table>

<%= link_to 'このメッセージを編集する', edit_message_path(@message), class: 'btn btn-light' %>
<%= link_to 'このメッセージを削除する', @message, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>